version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: sleep infinity
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      RAILS_ENV:   ${RAILS_ENV:-development}
      DB_HOST:     db
      DB_USERNAME: postgres
      DB_PASSWORD: password
