default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: sem7-agile_development

test:
  <<: *default
  database: sem7-agile_test

production:
  <<: *default
  database: sem7-agile_production
